name: flutter_requery
description: Flutter library for fetching, caching and invalidating asynchronous data.
version: 0.1.6
homepage: https://github.com/CoreLine-agency/flutter_requery
repository: https://github.com/CoreLine-agency/flutter_requery
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
