name: flutter_query
description: TODO
version: 0.0.1
author: mislavlukach
homepage: TODO
documentation: TODO

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  provider: ^4.3.2+3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
